application:
  subdomain: gbabeldocwebui
  upstreams:
    - location: /
      backend: http://gbabeldocui:7860/

services:
  gbabeldocui:
    # upstream: eaiu/gbabeldocwebui:1.1
    image: docker.1ms.run/eaiu/gbabeldocwebui:1.1
    environment:
      - PDF2ZH_WEB_UI=1
    binds:
      - /lzcapp/var/config:/root/.config/pdf2zh
      - /lzcapp/var/data:/app/data
    cpu_shares: 512
    mem_limit: 1024M
